- name: create vhost config
  copy:
    dest: /etc/apache2/sites-available/mywebsite.conf
    content: |
      <VirtualHost *:80>
          ServerName {{ server_name }}
          DocumentRoot {{ web_dir }}

          <Directory {{ web_dir }}>
              AllowOverride All
              Require all granted
          </Directory>

      </VirtualHost>

- name: enable site
  command: a2ensite mywebsite.conf
